development:
  adapter: postgresql
  encoding: unicode
  username: napoleon
  password: Password0
  database: lcrm_wasted_hours_development


test:
  adapter: postgresql
  encoding: unicode
  username: napoleon
  password: Password0
  database: lcrm_wasted_hours_test



production:
  adapter: postgresql
  encoding: unicode
  username: napoleon
  password: Password0
  database: lcrm_wasted_hours_production

